"""initial schema

Revision ID: 7b94c8322952
Revises: 
Create Date: 2026-07-06 22:44:43.168418

"""
from alembic import op
import sqlalchemy as sa


revision = '7b94c8322952'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_login_attempts'))
    )
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_attempts_ip'), ['ip'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_attempts_username'), ['username'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('semantic_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('current_version_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_semantic_views_created_by_users')),
    sa.ForeignKeyConstraint(['current_version_id'], ['semantic_view_versions.id'], name=op.f('fk_semantic_views_current_version_id_semantic_view_versions'), use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_semantic_views')),
    sa.UniqueConstraint('name', name=op.f('uq_semantic_views_name'))
    )
    op.create_table('sessions',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('user_agent', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_hash', name=op.f('pk_sessions'))
    )
    op.create_table('semantic_view_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('semantic_view_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('change_note', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('validation_status', sa.String(length=16), nullable=False),
    sa.Column('validation_messages', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_semantic_view_versions_created_by_users')),
    sa.ForeignKeyConstraint(['semantic_view_id'], ['semantic_views.id'], name=op.f('fk_semantic_view_versions_semantic_view_id_semantic_views')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_semantic_view_versions')),
    sa.UniqueConstraint('semantic_view_id', 'version_number', name=op.f('uq_semantic_view_versions_semantic_view_id'))
    )
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('semantic_view_id', sa.Integer(), nullable=False),
    sa.Column('pin_version_id', sa.Integer(), nullable=True),
    sa.Column('cron_expr', sa.String(length=64), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('overlap_policy', sa.String(length=8), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_schedules_created_by_users')),
    sa.ForeignKeyConstraint(['pin_version_id'], ['semantic_view_versions.id'], name=op.f('fk_schedules_pin_version_id_semantic_view_versions')),
    sa.ForeignKeyConstraint(['semantic_view_id'], ['semantic_views.id'], name=op.f('fk_schedules_semantic_view_id_semantic_views')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schedules'))
    )
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedules_next_run_at'), ['next_run_at'], unique=False)

    op.create_table('runs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('semantic_view_id', sa.Integer(), nullable=False),
    sa.Column('semantic_view_version_id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=True),
    sa.Column('triggered_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=False),
    sa.Column('report_path', sa.String(length=512), nullable=False),
    sa.Column('log_path', sa.String(length=512), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], name=op.f('fk_runs_schedule_id_schedules'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['semantic_view_id'], ['semantic_views.id'], name=op.f('fk_runs_semantic_view_id_semantic_views')),
    sa.ForeignKeyConstraint(['semantic_view_version_id'], ['semantic_view_versions.id'], name=op.f('fk_runs_semantic_view_version_id_semantic_view_versions')),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], name=op.f('fk_runs_triggered_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_runs'))
    )
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_runs_schedule_id'), ['schedule_id'], unique=False)
        batch_op.create_index('ix_runs_status_created', ['status', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_index('ix_runs_status_created')
        batch_op.drop_index(batch_op.f('ix_runs_schedule_id'))

    op.drop_table('runs')
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedules_next_run_at'))

    op.drop_table('schedules')
    op.drop_table('semantic_view_versions')
    op.drop_table('sessions')
    op.drop_table('semantic_views')
    op.drop_table('users')
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_attempts_username'))
        batch_op.drop_index(batch_op.f('ix_login_attempts_ip'))

    op.drop_table('login_attempts')
    # ### end Alembic commands ###
