"""add_snowflake_ref_to_semantic_views

Revision ID: 831d2bd78477
Revises: 7b94c8322952
Create Date: 2026-07-07 22:26:46.506548

"""
from alembic import op
import sqlalchemy as sa


revision = '831d2bd78477'
down_revision = '7b94c8322952'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('semantic_views', schema=None) as batch_op:
        batch_op.add_column(sa.Column('snowflake_ref', sa.String(length=256), server_default='', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('semantic_views', schema=None) as batch_op:
        batch_op.drop_column('snowflake_ref')

    # ### end Alembic commands ###
