-- walmart-opd-weekly-alsip.sql
-- Direct SQL query for the Walmart OPD Weekly Alsip pipeline.
--
-- Pulls the last 8 complete weeks from V_OPD_WEEKLY_ALSIP.
-- The pipeline uses TARGET (latest week) vs BASELINE (prior weeks) internally.
--
-- Grain: STORE_NBR × CORE_UPC_10 × WEEK_START
-- Source table: CCB_DATASCIENCE_DEV.WALMART_OPD.V_OPD_WEEKLY_ALSIP
-- Refresh: Table is materialized; refresh separately via scripts/create_opd_weekly_view.sql

SELECT
    WEEK_START,
    DAYS_IN_WEEK,
    STORE_NBR,
    CUSTOMER_DESC,
    DISTRIBUTION_CENTER_DESC,
    CORE_UPC_10,
    PRODUCT_ID,
    PRODUCT_DESC,
    PPG,
    BRAND,
    CATEGORY,
    FLAVOR,
    SIZE,
    ORIGINAL_ITEM_DESC,
    MANAGEDBY_SID,
    FTPR_NMRTR,
    FTPR_DNMNTR,
    FTPR_QTY,
    FTPR_RATE,
    NIL_PICK_QTY,
    NIL_PICK_COUNT,
    NIL_PICK_RATE,
    PRESUB_QTY,
    PRESUB_RATE_NMRTR,
    PRESUB_RATE_DNMNTR,
    PRESUB_RATE,
    POSTSUB_RATE_NMRTR,
    POSTSUB_RATE_DNMNTR,
    POSTSUB_RATE,
    SCHDL_NIL_PICK_QTY,
    SCHDL_NIL_PICK_RATE_NMRTR,
    SCHDL_NIL_PICK_RATE_DNMNTR,
    UNSCHDL_NIL_PICK_QTY,
    UNSCHDL_NIL_PICK_RATE_NMRTR,
    UNSCHDL_NIL_PICK_RATE_DNMNTR,
    DELIVERY_STOP_COUNT,
    AVG_DELIVERY_DURATION_MINS,
    TOTAL_DELIVERY_DURATION_MINS,
    IS_DELIVERY_ACTIVE_WEEK,
    MERCH_VISIT_COUNT,
    AVG_MERCH_DURATION_MINS,
    TOTAL_MERCH_DURATION_MINS,
    IS_MERCH_ACTIVE_WEEK
FROM CCB_DATASCIENCE_DEV.WALMART_OPD.V_OPD_WEEKLY_ALSIP
WHERE DAYS_IN_WEEK = 7  -- only complete weeks
  AND WEEK_START >= DATEADD('week', -8, DATE_TRUNC('week', CURRENT_DATE()))
ORDER BY WEEK_START, STORE_NBR, CORE_UPC_10
